blog/blog/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from .settings import DEBUG
from .views import LoginView, RegisterView, logout_view

urlpatterns = [
    path('admin/', admin.site.urls),
    path('login/', LoginView.as_view(), name='login'),
    path('register/', RegisterView.as_view(), name='register'),
    path('logout/', logout_view, name='logout'),
    path('', include("articles.urls")),
    path('', include("contacts.urls")),
]

if DEBUG:
    urlpatterns = urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/contacts/urls.py
from django.urls import path
from contacts.views import ContactUsView

urlpatterns = [
    path("contact/", ContactUsView.as_view(), name="contact_us")
]



blog/articles/models.py
from datetime import datetime
from django.db import models
from ckeditor.fields import RichTextField
from django.contrib.auth.models import User
from django.urls import reverse
from django.utils.text import slugify


def cover_uploader(instance, filename):
    filename = f'{instance.title[:15]}-Cover.png'
    return f'articles/{filename}'


class Writer(models.Model):
    """
    Writer model [ONLY WRITERS CAN EDIT OR CREATE ARTICLE]
    """
    user 					= models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.user.username 

    def get_absolute_url(self):
        return reverse("writer_articles", kwargs={"pk": self.id, "username": self.user.username})

class Article(models.Model):
    """
    Articles Model
    """
    title 					= models.CharField(max_length=150)
    text 					= RichTextField()
    cover 					= models.ImageField(upload_to=cover_uploader, blank=True, null=True)
    writer 					= models.ForeignKey(Writer, on_delete=models.CASCADE)
    timestamp 				= models.DateTimeField(default=datetime.now())

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("blog_details", kwargs={"pk": self.id, "slug": slugify(self.title)})

    class Meta:
        """
        order articles by id --> last to first
        """
        ordering = ["-id"]


blog/contacts/models.py
from django.db import models

class Contact(models.Model):
    """
    Contact-Us Model
    """
    name                    = models.CharField(max_length=60)
    email                   = models.EmailField()
    subject                 = models.CharField(max_length=150)
    message                    = models.TextField()

    def __str__(self):
        return self.subject


blog/articles/forms.py
from django import forms

from articles.models import Article


class NewArticleForm(forms.ModelForm):
    title = forms.CharField(widget=forms.TextInput(attrs={
        "class": "form-control",
        "placeholder": "Title"
    }), label="Title")

    text = forms.CharField(widget=forms.Textarea(attrs={
        "class": "form-control",
        "placeholder": "Article Body"
    }), label="Text")


    class Meta:
        model = Article
        fields = ["title", "text", "cover"]


blog/contacts/forms.py
from django import forms
from contacts.models import Contact


class ContactUsForm(forms.Form):
    """
    Contact_Us Form
    """
    name = forms.CharField(widget=forms.TextInput(attrs={
        "class": "form-control mb-2",
        "placeholder": "Enter your name...",
    }))
    email = forms.EmailField(widget=forms.EmailInput(attrs={
        "class": "form-control mb-2",
        "placeholder": "Enter your email...",
    }))
    subject = forms.CharField(widget=forms.TextInput(attrs={
        "class": "form-control mb-2",
        "placeholder": "Enter message subject...",
    }))
    message = forms.CharField(widget=forms.Textarea(attrs={
        "class": "form-control mb-2",
        "placeholder": "Enter your message...",
    }))

    def save(self):
        """
        get fields values and create a Contact Model instance
        """
        name = self.cleaned_data["name"]
        email = self.cleaned_data["email"]
        subject = self.cleaned_data["subject"]
        message = self.cleaned_data["message"]

        # Create Contact-Us instance
        contact_instance = Contact.objects.create(name=name, email=email, subject=subject, message=message)
        contact = contact_instance.save()
        return contact

blog/contacts/views.py
from django.shortcuts import redirect
from django.views.generic import FormView

from contacts.forms import ContactUsForm


class ContactUsView(FormView):
    """
    Contact-Us View
    """
    form_class = ContactUsForm
    template_name = "contact.html"

    def form_valid(self, form):
        """
        if Form is valid --> Save Form and Create an Instance of Contact Model
        """
        form.save()  # Create a Contact Model Instance
        return redirect("contact_us")  # redirect to previous page (Contact-Us Page)

blog/templates/article_create.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
{% include 'components/_headerReferences.html' %}
<body>
{% include 'components/header.html' %}

<div class="col-md-6 m-auto">
    <form enctype="multipart/form-data" class="mt-5" method="post" >
        {% csrf_token %}
        {{ form.writer.as_hidden }}
        <div class="mt-3">
            <label for="id_title" class="col-sm-2 col-form-label">Title:</label>
            {{ form.title }}
        </div>
        <div class="mt-3">
            <label for="id_text" class="col-sm-2 col-form-label">Text:</label>
            {{ form.text }}
        </div>
        <div class="mt-3 ">
            <label for="id_cover" class="col-sm-2 col-form-label">Cover:</label>
                {{ form.cover}}
        </div>
        <button type="submit" class="btn btn-primary mt-4 mb-5 col-md-12 p-3">Save</button>
    </form>
    {% if form.errors %}
        {% for field in form %}
            {% if field.errors %}
                {% for error in field.errors %}
                    <div class="alert alert-danger text-center">{{ field }} - {{ error|escape }}</div>
                {% endfor %}
            {% endif %}
        {% endfor %}
    {% endif %}
</div>

{% include 'components/footer.html' %}
{% include 'components/_footerReferences.html' %}

<script>
    let cover = document.getElementById("id_cover");
    cover.classList.add("form-control");
</script>

</body>
</html>

blog/templates/article_details.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
{% include 'components/_headerReferences.html' %}

<body>
{% include 'components/header.html' %}
<!-- Page Header-->
<header class="masthead" style="background-image: url({% if object.cover %}{{ object.cover.url }}{% endif %});">
    <div class="container position-relative px-4 px-lg-5">
        <div class="row gx-4 gx-lg-5 justify-content-center">
            <div class="col-md-10 col-lg-8 col-xl-7">
                <div class="post-heading">
                    <h1>{{ object.title }}</h1>
                    <span class="meta mt-5">
                                Posted by
                                <a href="#!">{{ object.writer }}</a>
                                on August 24, 2021
                            </span>
                </div>
            </div>
        </div>
    </div>
</header>
<!-- Post Content-->
<article class="mb-4">
    <div class="container px-4 px-lg-5">
        <div class="row gx-4 gx-lg-5 justify-content-center">
            <div class="col-md-10 col-lg-8 col-xl-7">
                {{ object.text|safe }}
            </div>
        </div>
    </div>
</article>
{% include 'components/footer.html' %}
{% include 'components/_footerReferences.html' %}
</body>

</html>

blog/templates/contact.html
{% load  static %}
<!DOCTYPE html>
<html lang="en">
{% include 'components/_headerReferences.html' %}
<style>
    #id_message {
        height: 150px;
    }
</style>
<body>
{% include 'components/header.html' %}
<!-- Main Content-->
<!-- Page Header-->
<header class="masthead">
    <div class="container position-relative px-4 px-lg-5">
        <div class="row gx-4 gx-lg-5 justify-content-center">
            <div class="col-md-10 col-lg-8 col-xl-7">
                <div class="page-heading">
                    <h1>Contact Me</h1>
                    <span class="subheading">Have questions? I have answers.</span>
                </div>
            </div>
        </div>
    </div>
</header>
<main class="mb-4">
    <div class="container px-4 px-lg-5">
        <div class="row gx-4 gx-lg-5 justify-content-center">
            <div class="col-md-10 col-lg-8 col-xl-7">
                <h2 class="text-center mt-5">Contact Us</h2>
                <div class="my-5">
                    <form id="contactForm" method="post">
                        {% csrf_token %}
                        <div class="form-floating">
                            {{ form.name }}
                            <label for="id_name">Name</label>
                            <div class="invalid-feedback" data-sb-feedback="id_name:required">A name is required.</div>
                        </div>
                        <div class="form-floating">
                            {{ form.email }}
                            <label for="id_email">Email address</label>
                            <div class="invalid-feedback" data-sb-feedback="id_email:required">An email is required.
                            </div>
                            <div class="invalid-feedback" data-sb-feedback="email:email">Email is not valid.</div>
                        </div>
                        <div class="form-floating">
                            {{ form.subject }}
                            <label for="id_subject">Subject</label>
                            <div class="invalid-feedback" data-sb-feedback="id_subject:required">A Subject is
                                required.
                            </div>
                        </div>
                        <div class="form-floating">
                            {{ form.message }}
                            <label for="id_message">Message</label>
                            <div class="invalid-feedback" data-sb-feedback="id_message:required">A message is required.
                            </div>
                        </div>
                        <br/>
                        <!-- Submit Button-->
                        <button class="btn btn-primary text-uppercase col-md-12 p-3" id="submitButton" type="submit">Send
                        </button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</main>
{% include "components/footer.html" %}
{% include "components/_footerReferences.html" %}
</body>
</html>

blog/templates/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
{% include 'components/_headerReferences.html' %}

<body>
{% include 'components/header.html' %}
<!-- Page Header-->
<header class="masthead" style="background-image: url('{% static 'img/home-bg.jpg' %}')">
    <div class="container position-relative px-4 px-lg-5">
        <div class="row gx-4 gx-lg-5 justify-content-center">
            <div class="col-md-10 col-lg-8 col-xl-7">
                <div class="site-heading">
                    <h1>My Blog</h1>
                    <span class="subheading">A Simple Weblog that created with Django</span>
                </div>
            </div>
        </div>
    </div>
</header>
<!-- Main Content-->
<div class="container px-4 px-lg-5">
    <div class="row gx-4 gx-lg-5 justify-content-center">
        <div class="col-md-10 col-lg-8 col-xl-7">
            <!-- Post preview-->
            {% for article in object_list %}
                <div class="post-preview">
                    <a href="{{ article.get_absolute_url }}">
                        <h2 class="post-title">{{ article.title }}</h2>
                        <h3 class="post-subtitle">{{ article.text|safe|truncatewords:10 }}</h3>
                    </a>
                    <p class="post-meta">
                        Posted by
                        <a href="{{ article.writer.get_absolute_url }}">{{ article.writer }}</a> on {{ article.timestamp }}
                    </p>
                </div>
                <!-- Divider-->
                <hr class="my-4"/>
            {% endfor %}
            <!-- Pager-->

            <div class="d-flex justify-content-end mb-4">
                {% if page_obj.has_previous %}
                    <a class="btn btn-primary me-3 text-uppercase" href="?page={{ page_obj.previous_page_number }}">← Newer Posts</a>
                {% endif %}
                {% if page_obj.has_next %}
                    <a class="btn btn-primary text-uppercase" href="?page={{ page_obj.next_page_number }}">Older Posts →</a></div>
                {% endif %}
        </div>
    </div>
</div>
<!-- Footer-->
{% include 'components/footer.html' %} {% include 'components/_footerReferences.html' %}
</body>

</html>

blog/templates/login.html
<!DOCTYPE html>
<html lang="en">
{% include 'components/_headerReferences.html' %}

<body>
<div class="container">
    <div class="row">
        <form action="" method="post">
            <div class="d-grid gap-2 col-6 mx-auto">
                {% csrf_token %}
                {{ form.username }}
                {{ form.password }}
                {% if form.errors %}
                    {% for error in form.non_field_errors %}
                        <div class="alert alert-danger text-center">{{ error|escape }}</div>
                    {% endfor %}
                {% endif %}

                <div class="d-grid gap-2 col-6 mx-auto mt-3">
                    <button class="btn btn-success" type="submit">Login</button>
                </div>
            </div>
        </form>
    </div>
</div>

{% include 'components/_footerReferences.html' %}
</body>

</html>

blog/templates/register.html
<!DOCTYPE html>
<html lang="en">
{% include 'components/_headerReferences.html' %}

<body>
<div class="container">
    <div class="row">
        <form action="" method="post">
            <div class="d-grid gap-2 col-6 mx-auto">
                {% csrf_token %}
                {{ form.email }}
                {{ form.username }}
                {{ form.password1 }}
                {{ form.password2 }}

                {% if form.errors %}
                    {% for field in form %}
                        {% if field.errors %}
                            {% for error in field.errors %}
                                <div class="alert alert-danger text-center">{{ error|escape }}</div>
                            {% endfor %}
                        {% endif %}
                    {% endfor %}
                {% endif %}


                <div class="d-grid gap-2 col-6 mx-auto mt-3">
                    <button class="btn btn-success" type="submit">Login</button>
                </div>
            </div>
        </form>
    </div>
</div>

{% include 'components/_footerReferences.html' %}
</body>

</html>